version: '3.4'

services:
  ludustack-web:
    container_name: ludustack-web
    image: ${DOCKER_REGISTRY-}ludustack-web
    build:
      context: .
      dockerfile: LuduStack.Web/Dockerfile
    networks:
      - ludustack-network
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'ludustack-db'
  ludustack-db:
      container_name: ludustack-db
      image: mongo:latest
      hostname: ludustack-db
      networks:
        - ludustack-network
      ports:
        - '27017:27017'
      env_file:
        - .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
      healthcheck:
        test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
        interval: 10s
        start_period: 30s
      command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
networks:
  ludustack-network:
    driver: bridge